# Generated by Django 4.1 on 2024-09-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_status', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('house_number', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.accountstatus')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('minimum_bid', models.IntegerField()),
                ('maximum_bid', models.IntegerField()),
                ('price', models.IntegerField()),
                ('buy_now', models.BooleanField(default=False)),
                ('promotion', models.BooleanField(default=False)),
                ('auction_start_date', models.DateField()),
                ('auction_end_date', models.DateField()),
                ('number_of_views', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.category')),
            ],
        ),
    ]
