# Generated by Django 4.1 on 2024-10-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionEvalution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_rating', models.IntegerField()),
                ('sellers_comment', models.TextField()),
                ('buyer_rating', models.IntegerField()),
                ('buyers_comment', models.TextField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.auction')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.useraccounts')),
            ],
        ),
    ]
