# Generated by Django 4.1 on 2024-10-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_transactionevalution_advertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_end_date',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='auction_start_date',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='buy_now',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='maximum_bid',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='minimum_bid',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='number_of_views',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='price',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='useraccounts',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='useraccounts',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='useraccounts',
            name='address',
        ),
        migrations.RemoveField(
            model_name='useraccounts',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraccounts',
            name='created',
        ),
        migrations.RemoveField(
            model_name='useraccounts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useraccounts',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccounts',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='useraccounts',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='useraccounts',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='useraccounts',
            name='password',
        ),
        migrations.RemoveField(
            model_name='useraccounts',
            name='zip_code',
        ),
    ]
