# Generated by Django 5.1.1 on 2024-10-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_useraccounts_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionevaluation',
            name='auction',
        ),
        migrations.AlterField(
            model_name='addauction',
            name='auction_end_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='TransactionEvaluation',
        ),
    ]
