# Generated by Django 5.1.1 on 2025-03-03 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_buyerevaluation_sellerevaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addauction',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 10, 2, 42, 20, 333730, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
