# Generated by Django 5.1.1 on 2024-10-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_advertisement_auction_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='promotion',
            field=models.BooleanField(default=True),
        ),
    ]
