# Generated by Django 5.1.1 on 2024-10-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_remove_transactionevaluation_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addauction',
            name='auction_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
