# Generated by Django 4.1 on 2024-10-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='advertisement_photos/'),
        ),
    ]
