# Generated by Django 5.1.1 on 2024-10-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_advertisement_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='promotion',
            field=models.BooleanField(default=True),
        ),
    ]
