# Generated by Django 4.1 on 2024-10-02 17:56

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_advertisement_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='photo',
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_end_date',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_start_date',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='auction',
            name='buy_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewer.category'),
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='auction',
            name='maximum_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='minimum_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
    ]
