# Generated by Django 4.1 on 2024-10-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_remove_advertisement_photo_auction_auction_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='maximum_bid',
        ),
    ]
