# Generated by Django 5.1.1 on 2024-10-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_advertisement_buy_now_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
