# Generated by Django 5.1.1 on 2024-10-07 15:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_advertisement_buy_now'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='Add_auction',
        ),
    ]
