# Generated by Django 5.1.1 on 2024-10-02 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_remove_auction_maximum_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
