# Generated by Django 5.1.1 on 2024-10-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_alter_auction_auction_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='pocet_zobrazeni',
            field=models.IntegerField(default=0),
        ),
    ]
