# Generated by Django 5.1.1 on 2024-10-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_auction_pocet_zobrazeni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='number_of_views',
        ),
    ]
