# Generated by Django 5.1.1 on 2024-10-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_rename_add_auction_addauction_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='addauction',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addauction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
