# Generated by Django 5.1.1 on 2024-10-03 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_remove_auction_number_of_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_end_date',
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_duration_hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
