# Generated by Django 5.1.1 on 2024-10-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_addauction_original_price_alter_addauction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='addauction',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
