# Generated by Django 5.1.1 on 2024-10-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_remove_auction_auction_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_duration_hours',
            field=models.IntegerField(default=2),
        ),
    ]
