# Generated by Django 4.1 on 2024-10-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_profile'),
        ('viewer', '0011_addauction_last_price'),
    ]

    operations = [
    ]
