# Generated by Django 5.1.1 on 2024-10-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_alter_auction_auction_duration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_duration_hours',
            field=models.IntegerField(default=1),
        ),
    ]
