# Generated by Django 5.1.1 on 2024-10-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_merge_0009_profile_0011_addauction_last_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addauction',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='addauction',
            name='price',
        ),
        migrations.AddField(
            model_name='addauction',
            name='auction_type',
            field=models.CharField(choices=[('buy_now', 'Buy Now'), ('place_bid', 'Place Bid')], default='place_bid', max_length=10),
        ),
        migrations.AddField(
            model_name='addauction',
            name='penultimate_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='addauction',
            name='start_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addauction',
            name='buy_now',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addauction',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
