# Generated by Django 5.1.1 on 2024-10-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_remove_addauction_original_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addauction',
            name='minimum_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
