# Generated by Django 5.1.1 on 2024-10-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_alter_auction_auction_duration_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='pocet_zobrazeni',
            new_name='number_of_views',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='auction_duration_hours',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='auction_start_date',
        ),
    ]
