# Generated by Django 5.1.1 on 2024-10-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_alter_addauction_minimum_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addauction',
            old_name='buy_now',
            new_name='buy_now_price',
        ),
    ]
