# Generated by Django 5.1.1 on 2024-10-03 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_rename_pocet_zobrazeni_auction_number_of_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_duration_hours',
            field=models.FloatField(default=24),
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
