# Generated by Django 5.1.1 on 2024-10-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_rename_buy_now_addauction_buy_now_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='add_auction',
            new_name='auction',
        ),
    ]
