# Generated by Django 5.1.1 on 2024-10-06 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_auction_auction_duration_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_duration_hours',
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
