# Generated by Django 5.1.1 on 2024-10-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_rename_add_auction_bid_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addauction',
            old_name='last_price',
            new_name='previous_price',
        ),
        migrations.RenameField(
            model_name='addauction',
            old_name='penultimate_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='addauction',
            name='start_price',
        ),
    ]
