# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from selenium import webdriver
from selenium.webdriver.common.keys import Keys

# Spustí prohlížeč (např. Chrome)
driver = webdriver.Chrome()

# Otevře stránku
driver.get("http://127.0.0.1:8000")

# Například můžeš vypsat, zda je stránka otevřená
print("Stránka byla úspěšně načtena:", driver.title)

class Test123():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_123(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(868, 912)
    self.driver.find_element(By.LINK_TEXT, "Přihlásit se").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("1234")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3)").click()
    self.driver.find_element(By.ID, "id_password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".u-btn-1").click()
    self.driver.find_element(By.LINK_TEXT, "Place Bid").click()
    self.driver.find_element(By.NAME, "new_bid").click()
    self.driver.find_element(By.NAME, "new_bid").send_keys("10000")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    self.driver.find_element(By.LINK_TEXT, "Back to Previous Page").click()
    self.driver.find_element(By.LINK_TEXT, "Back to Previous Page").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-link").click()
  
